### ISSUE TITLE
Send e-mail to user when he subscribes to an activity

### ISSUE THREAD

**Issue by krico** [krico/jas#142]
Right now on the subscribe implementation, a very minimal e-mail is sent to the owners.

This should be changed into a nicely formatted html e-mail that gets sent to the user.

The same formatting can then be used when notifying the owners.

Also note that upon the implementation of #143 (payment) the e-mail template might need to change a little.

**Comment by wszarmach** [comment]
There is a tool that checks if the html will display properly in the main email clients http://premailer.dialect.ca/

**Comment by krico** [comment]
That is cool.  But remember you still need to have the text/plain version as a second mime attachment to the e-mail.  

Also, the html in the e-mail needs to be "pretty"  but **simple** :-)

I don't think people care too much about the format in the email, especially if they are readin in their mobile...

**Comment by krico** [comment]
This issue is now also linked to #28 when we send the password recovery e-mail

**Comment by krico** [comment]
Just to revive something I just ran accross around [these todo's](https://github.com/krico/jas/blob/master/schedule/schedule-appengine/src/main/java/com/jasify/schedule/appengine/spi/AuthEndpoint.java#L247) :-)
