### ISSUE TITLE
If I forget my password I have no forgotten password option

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#150]
Wasnt sure whether there was meant to be a forgotten password option yet or whether this is for later, but I noticed that there wasnt one because I have actually forgotten mine so I was looking for it. As it wasnt there I logged in with facebook instead. But some people like myself i.e. scatterbrains will need a forgotten password option at some point soon.

**Comment by krico** [comment]
This issue will be fixed with #28 ...
