### ISSUE TITLE
Org name should be available on search results by activity id

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#157]
When I search by activity type eg Metafit, I would need each record to say which org it belongs to. For instance Metafit could be offered by Jayne and it could be offered by Goldie's Gym.

So I should be able to say next to each record something like

Provider: No Excuses Zurich
From: 01/01/2015 07:30 CET
To: 01/01/2015 08:00 CET
Location: Hallenbad City, Sihlstrasse 71, 8001 Zurich
Price: 20 CHF
Description: bla bla

Reason being that for instance Jayne has a good reputation so people would sign up because they see it is offered by her.

**Comment by wszarmach** [comment]
Replaced by duplicate #352
