### ISSUE TITLE
Password Recovery followed by sign in should show landing page

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#168]
Currently after signing in after password recovery the current page continues to show the password change page.

![image](https://cloud.githubusercontent.com/assets/9398950/6050344/0052b618-acbf-11e4-925c-f0574f9c3f21.jpg)

**Comment by krico** [comment]
since this is an old issue I am not 100% sure it will be resolved by the change I made, so please reopen it if it is still an issue after the next release.
