### ISSUE TITLE
I need to receive the booking mails

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#175]
I was doing a demo video for my MBA and I booked a class but I didnt receive a mail. I think Waldemar gets the mails, but I also need to get them as I would need to notify Jayne that someone has booked and coming to her class.

Also the user who books should get an email too. So in this case I should have received 2 mails - one because i am admin and two as the user who booked. I also noticed that the subscription on jasify still said 0 of 20 after I had booked. On mywayfit it correctly displayed 19/20. Perhaps the field on jasify is not updated?

**Comment by krico** [comment]
I added your hotmail e-mail to the prod system.  You should now get all e-mails that waldemar gets.
