### ISSUE TITLE
"Sign In" should be displayed first rather than "Create Account" 

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#177]
In terms of usability the first screen should be sign in rather than create account. Because you only create an account one time but after that you sign in many times. So the usability would be better that the default screen is the sign in one, with a link to create account if you dont have one already. This is how most other systems do it too.

**Comment by krico** [comment]
The concept: if the user never logged into the system before using this browser (local browser cache) he gets prompted with *Create Account*, else he gets prompted with "Sign In".
