### ISSUE TITLE
Paypal handling fee of only 0.35%?

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#198]
On the balance part it says the fees are

0.35% plus CHF 0.55

I think this is a typo right? As when I checked the fees are higher than 0.35%

**Comment by krico** [comment]
I guess the 0.35% is a typo for 3.5%
I hope the calculations are correct :-)
![image](https://cloud.githubusercontent.com/assets/6952185/7012868/a7b3fcbc-dcb4-11e4-9469-17b812eb98d9.png)
