### ISSUE TITLE
In the repeat functionality the day of the start date should be selected by default

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#200]
The repeat functionality has a days option for you to select on which days you want to repeat. But by default none is selected. I think what makes most sense is to by default select the day that corresponds to the start date eg if the start date is a Tuesday the day Tuesday should be already selected in the days part of the form.

Also the Every option I think needs an additional label so that it says eg

Every .....  days

or

Every ..... weeks

Because without this label it relies on you remembering whether you previous selected repeat weekly or daily. In fact does it make sense to have to select Repeat daily or Repeat Weekly because the fields give you full flexibility anyhow. I think Repeat Yes or No makes most sense and then in the Every you can select days or weeks.

What happens if you select repeat "days" Tuesday and repeat "every" as 3 days. How does that work in this case, because repeating every 3 days would mean you are not always on a Tuesday? I think we somehow need to simplify this whole section to avoid any confusions like this as to what things mean. eg you either mean repeat every x days or you mean repeat every Tuesday but you cannot mean both at once can you?

**Comment by wszarmach** [comment]
I think this is a couple of issues in one issue so I will split them up.
With regards to repeat Daily or Weekly it might make sense to simplify. For now to explain the logic it works as follows;
Count is how many entries will be added
Until Date is until which date the logic will attempt to create new activities.
Note that in all cases the server will only allow the client to create 25 activities
Repeat Daily with Every will allow you to create an activity on the start date and than add a repeat activity every X days. So for example if today is Monday and you choose every 7 you will have activities on Mondays.
Repeat Weekly lets you select multiple days to create an activity per week and than add repeat activities every x weeks. So for example if you want to add an activity every Tuesday and Thursday for 3 weeks you would select T,W Every 1 with Until date in 3 weeks. If on the other hand you wanted to create an activity on Monday and Wednesday every fortnight you would select M,W Every 2.
