### ISSUE TITLE
Link payment to the activities but leave an option to pay at the door

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#205]
I see that there is now a balance option so that you can pay a certain amount of money into a jasify account. I think the next step though is to link payment to classes.

When the user gets to the point of booking a class they should have the option to pay with paypal or to pay at the door. This is the first step in meeting Jayne's requirements as the users who only book single classes can pay for them like this. Those that purchase packages from her can just tick the pay at door option.

At the beginning I think it is more likely that people will just pay for single classes than to put credit into the jasify account. But I can imagine that it would make sense to check at the time of booking whether the user has credit in their jasify account, and if so give them the option of using that credit to pay for the class (rather than paying even more into paypal) or to pay at the door (as again they might be buying Jayne's packages in which case they actually get a better price than the single class price so this is why we still need the pay at door option).

In terms of paypal accounts, we need to chain the payments so that the jasify cut goes to the jasify paypal account and then the remainder goes to the provider. For step 1 where the only provider is Jayne we can always just credit the full amount into her paypal account, as if you havent already implemented chaining I can imagine it will take you longer to implement.

**Comment by krico** [comment]
Relates to #228

**Comment by krico** [comment]
This was resolved.
