### ISSUE TITLE
Couldnt sign in with facebook until I shut down Chrome and restarted it

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#210]
There is an issue signing in with facebook on Chrome when you use multiple tabs. To reproduce:

1) Sign in with facebook
2) Close tab WITHOUT LOGGING OUT FIRST
3) Open new tab
4) Sign in with facebook

At step 4 it will fail saying it cannot authenticate

**Comment by krico** [comment]
I've just deployed a new version to prod that fixed #211 but I think it could also have fixed this one.  Could you please try to reproduce again?

![image](https://cloud.githubusercontent.com/assets/6952185/6878336/9c1b4e80-d4dc-11e4-8d8f-fdcc76e07bf6.png)

**Comment by pauljanes** [comment]
Double sign in with facebook seems to be fixed now. Seems to also work on firefox now too

**Comment by krico** [comment]
Awesome!  That ngStorage module was the wrong choice.
