### ISSUE TITLE
In list of people subscribed to activity I see "pauljanes" where I would expect to see an email

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#216]
In the screenshot below you can see I used 2 accounts to sign up for an activity so that the list would show 2 subscribers. This part works well. The only thing is that the provider will want to see the name and the email incase they need to contact them eg change of class time, cancellation of class etc.

The account that I created with email and password I see the email displayed in the "Name" column, but the account that I created by linking to my Facebook I see "pauljanes" in the "Name" column where I would expect to see an email. Why do we call it Name by the way if it is an email?

![screen shot 2015-03-28 at 00 12 58](https://cloud.githubusercontent.com/assets/9402268/6878496/49b68dd2-d4df-11e4-8c55-cb831aeedfd2.png)

**Comment by wszarmach** [comment]
Although I have to double check I dont think I am displaying the email but the "username". If you create an account via email than the username is the email.
It might be better not to show the email of the subscriber but to allow the publisher to send an email from Jasify.
Given the above it might be better to supress the username.

**Comment by pauljanes** [comment]
Its pretty normal that the provider can see the email addresses of the people going to her class, as in this way they are her clients. Why would we hide them? For me hiding them is the wrong approach. I would also say we should have users phone numbers and display that too. None of the other systems hide email addresses. Otherwise the provider will just make the user fill in additional forms at the class to get the contact info, which is kind of annying for users as they will be thinking "why do i have to fill this out as you should already have my details from when i booked"
