### ISSUE TITLE
Deleting an activity type screws up the org to which it belongs

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#219]
I created Ghettogym (ahFzfmphc2lmeS1zY2hlZHVsZXIUCxIMT3JnYW5pemF0aW9uGLLzeww), and added some activities of type Bootcamp. Then as I could not edit the activitytype Bootcamp, I deleted it and planned on adding a new activitytype called Bootcamp Ghettogym (to get around the fact that activitytypes are defined per org and not globally like they should be), but after I deleted it, the org appears to be screwed. Can you please investigate the above org and see what kind of strange state it is in now - because it has activities of a type that has been deleted. Also I could not get the activities via mywayfit classes page for this org any longer.

My workaround in the end was to create an entirely new org "Ghetto Gym" - note the space and to add all the activities again. But this logic of deleting activitytypes needs to be looked at in more detail.

**Comment by wszarmach** [comment]
Cleaned up directly in datastore
