### ISSUE TITLE
After password reset and sign in, password recovery screen should disappear

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#230]
Jayne did the password recovery because she forgot her password and she thought that the password reset did not work and asked me to help her. After looking at the issue it is because once you do the password reset and sign in, you still see the password reset dialog. The only way to know that the sign in now worked is by looking at the menu on the top right and seeing that you now have the various options.

To avoid confusion, when you do a password reset and then sign in, you could show a screen that says you are now signed in or something like this, instead of the password recovery screen.

**Comment by krico** [comment]
since this is an old issue I am not 100% sure it will be resolved by the change I made, so please reopen it if it is still an issue after the next release.
