### ISSUE TITLE
Feedback from Jayne about cursor hover text not fully visible - layout problem

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#235]
"When I put my cursor over what I want to click it isn’t in the right place and I can’t see all of the letters in the word see screen shot I presume it says Create but I can only see ate."
 
![image001 4](https://cloud.githubusercontent.com/assets/9402268/7084890/06c828bc-df72-11e4-8a34-98a330356573.png)

**Comment by wszarmach** [comment]
With the new layout this issue is fixed
