### ISSUE TITLE
Do not send out subscription emails until paypal payment successfully made

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#251]
At present if you opt for the pay with paypal option you get a subscription mail before you login even to paypal.

You mentioned this is to make sure place is reserved.

This needs to move to a timed reservation where it says for instance "You have 10 mins to complete this transaction before your reservation will be released". Then you would only send out subscription mails if you get successful response from paypal. Otherwise if you dont get successful response from paypal within the time limit, you release the place and no emails will have been sent out.

From a legal point of view, it is important that the client does not receive a confirmation email saying they are subscribed if they have not paid and the provider has disabled the pay at door option. Because the confirmation mail might then be considered legally binding. And then you have a problem, because the client has proof that he has been given a place, and the provider might say well no you cant come because you havent paid and I have given the place to someone else.

**Comment by wszarmach** [comment]
This issue is linked to #182
