### ISSUE TITLE
Activity with currency but no price throws exception on checkout

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#260]
Probably null to primitive conversion.
Question; should price always be set?

**Comment by pauljanes** [comment]
There are some classes that are free. For instance some of the pregnancy fitness classes are free. So classes with price of zero should be possible and this needs to be taken into account at payment stage too. As no payment is needed of price is zero.

Even though we cant make money out of free classes, having them as an offering brings more users to our platform. So it brings a benefit to be able to offer them

**Comment by wszarmach** [comment]
price is now a mandatory field (allows 0 up) therefore this is no longer an issue
