### ISSUE TITLE
Introduce a template engine for e-mail generation

### ISSUE THREAD

**Issue by krico** [krico/jas#271]
I think main available options are:
 * [Velocity](https://velocity.apache.org/)
 * [Freemaker](http://freemarker.org/)
 * [Google Closure Templates](https://developers.google.com/closure/templates/)
 * [StringTemplate](http://www.stringtemplate.org/)

Check this [template benchmark](https://github.com/PerfectCarl/template-engine-benchmarks/blob/master/README.md)

**Comment by wszarmach** [comment]
implemented
