### ISSUE TITLE
Filled values overwritten on edit activity

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#277]
When you edit an activity, you are overwriting the start and end date with todays date and time.

Also when you enter a description for an activity and then select the activity type, you overwrite the description that was entered with the default description associated with that activity type.

If fields are filled they should not be overwritten.

**Comment by wszarmach** [comment]
If you have two activities;
* Type=Squash, Description=Racket sport, Price=20
* Type=Water Polo, Description=Water based activity, Price=10
You make a Squash activity then decide to edit it and change it to Water Polo is it not more convenient of the details change?

**Comment by wszarmach** [comment]
I have done a push to fix the date issue but not the description field. If you would still like that behaviour changed please raise a separate issue but lets discuss it first.

**Comment by pauljanes** [comment]
The problem is for instance in the case of Jayne that the description includes location-specific info eg entry to Hallenbad is required. The activity description could only include this info if she defines 2 separate activity types eg Metafit Hallenbad and Metafit Holmes Place.

The idea solution is to define a new field for extra info where stuff like this could go. Or location specific info somehow linked to location.

Until you have these new fields, I think it is better to not overwrite it. Else you are forcing the provider to essentially define activity types per location.

At the moment activity description is actually activity description plus extra info
