### ISSUE TITLE
Change "Subscriptions" label as users find it confusing

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#291]
When a provider is creating an activity they see a label saying "Subscriptions". They find this confusing as subscriptions is when someone has subscribed eg we have 5 subscriptions means that 5 people have subscribed. It should be called something more meaningful like "Available places"

**Comment by wszarmach** [comment]
How about changing subscriptions to capacity?
Heres how the create activity screen would look

![screen shot 2015-05-10 at 02 18 48](https://cloud.githubusercontent.com/assets/9398950/7552560/fe863580-f6ba-11e4-9ded-da490db1de24.png)

and this is the create activity type screen

![screen shot 2015-05-10 at 02 03 13](https://cloud.githubusercontent.com/assets/9398950/7552562/0a6fd392-f6bb-11e4-9d2f-a39c1e888ea1.png)

**Comment by wszarmach** [comment]
I will make the above change and close the issue. If you prefer available places please reopen and I will make the change
