### ISSUE TITLE
On admin users view, the tooltip on the edit button is misplaced

### ISSUE THREAD

**Issue by krico** [krico/jas#295]
If you scroll down and then hover over the edit button, the tooltip shows up on the wrong line.  In the image below, my mouse was over sample4 and the tooltip shows on sample1

![image](https://cloud.githubusercontent.com/assets/6952185/7552108/fe59eae2-f6a2-11e4-9442-9ca472ac511c.png)

**Comment by pauljanes** [comment]
Ah yes this is what Jayne also mentioned. That she hovered over something and Create was off the screen, showing only as reate

**Comment by dragonflypl** [comment]
This is a bug in angular-material, i've reported it. For the time being, i'll disable angular-material tooltip and simply show title.
