### ISSUE TITLE
Admins of orgs (eg Jayne) need to be able to add user to class

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#302]
I discussed this will Wally and he asked me to raise an issue for it. It was part of the feedback from meeting with Jayne but he is issue-drive he says :) She wanted this for her go live.

Real use-case for Jayne: User books her 12 class Bootcamp package for her evening bootcamp class. They cant make it to one particular class (something comes up eg baby gets sick) so they ask her can they swap one evening class for one morning class. She usually says ok to this provided she has spaces in the morning class that they want to attend, as she wants to give them good customer service.

As Wally mentioned, Jayne can already cancel a user as an org admin. But then she needs to be able to add the user to the morning class. Therefore we need an "add user to class" (for want of a better name) function for org admin. No payment is required as this is an admin function. So it is basically just checking there is an available space in that class, and if so reducing the number of available spaces by 1 on the backend and adding that user to the list of the subscribers for that activity.

As Wally and I discussed, we might later want a "move" function rather than a 2 step process. But at least with cancel and then add we can give Jayne what she needs with less work for now.

I realise that Jayne can get around this without an add function. eg by cancelling the user from the evening class, reducing the capacity of the morning class by 1 and telling them to just turn up at her morning class. But this is extremely hacky as not everything is then recorded in the system. She wants to be able to see who attended her classes in our system and not have to maintain a separate list elsewhere.

The add function can also be used for those that just turn up at her class spontaneously so that she can record everyone who attended in our system.

**Comment by wszarmach** [comment]
We need to consider this. An org admin can currently only see the users details while they are subscribed. If an org admin is allowed to add a user to an activity they will be bypassing the payment model. To avoid making changes in those areas the move functionality might be needed to start with.

**Comment by wszarmach** [comment]
After a quick chat with the CTO we will open up the user info to org admins by showing users that have in the past made a subscription to the org

**Comment by pauljanes** [comment]
Sounds like a good solution. The cto must be a wise owl

**Comment by pauljanes** [comment]
One extra thought. We should allow admin of the org to add the user even if the class is full. They are in charge of the org after all. But we should display a warning like "The activity is full. Adding this user will automatically increase the capacity by 1. Are you sure?"

There are reasons that the org admin might want to make a special exception. The class size might normally be 12, but they might as a one off allow someone else to join - maybe to try it out. So in that class they might want to add a user even when they already have 12 subscribers, and in this case the capacity should be increased to 13 if the org admin uses the add user option and confirms the warning

**Comment by wszarmach** [comment]
This issue is linked to #182
