### ISSUE TITLE
Activity Package with item count = activities in list does not need user to choose activities

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#314]
If an Activity Package has an item count equal to the number of selectable activities than all activities should be automatically selected.

**Comment by pauljanes** [comment]
Yeah this is what I was thinking too

**Comment by dragonflypl** [comment]
Maybe a checkbox "Select All" next to Item Count field. This way you don't need to put correct number into Item Count

**Comment by dragonflypl** [comment]
Also, I thought I understand what Item Count means, but now I don't  :) Could you please explain its purpose / validation rules etc?

**Comment by wszarmach** [comment]
the activity package can be thought of as a discount bulk purchase of activities. The publisher specifies the number of activities that are in the package through "item count". The publisher also adds the activity choices. The number of choices must be greater or equal to "item count". When the subscriber books a package  they must choose a subset from the activities that the publisher added up to "item count". If the publisher added 10 activities and set "item count" to 10 than the subscriber will select all 10 activities but as an enhancement this could be automatically done for the subscriber .

**Comment by dragonflypl** [comment]
Ok, now it is clear.

**Comment by wszarmach** [comment]
Sorry its been pointed out to me that I wrote something wrong in the description.
The Publisher can add 1 or more activities to a package. The Item Count specifies how many of those activities the subscriber is allowed to select.

**Comment by wszarmach** [comment]
To insure there is no misunderstanding we have decided to add a "Select All" button. This button should only be visible if the number of selectable activities is less than or equal to Item Count.

**Comment by dragonflypl** [comment]
Already implemented
