### ISSUE TITLE
Implement handling of ActivtyPackageExecution in MailParser 

### ISSUE THREAD

**Issue by krico** [krico/jas#316]
Starting from `ShoppingCartPaymentWorkflow` you have
1. Implement support for `ActivityPackageSubscription` on createPublisherSubscriptionEmail, maybe mention the ActivityPackage this was subscribed as part of, and make sure the price etc make sense
```java
    private void notifyPublisher(List<Subscription> subscriptions, List<ActivityPackageExecution> executions) {
    ....
    MailParser mailParser = MailParser.createPublisherSubscriptionEmail(packageSubscriptions.get(i));
```

2. Add handling of `executions` on `createSubscriberSubscriptionEmail`
```java
MailParser mailParser = MailParser.createSubscriberSubscriptionEmail(subscriptions, executions);
```

3. Same for `createJasifySubscriptionEmail`
```java
MailParser mailParser = MailParser.createJasifySubscriptionEmail(subscriptions, executions);
```

**Comment by wszarmach** [comment]
This was closed as part of ActPac-Mail branch. I must have forgotten to add the link
