### ISSUE TITLE
Sign in with Email shows green tick incorrectly

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#326]
You get a green tick next to the username field if it has one character and a green tick next to the password field if it has one character. This tick suggests that you have done everything correctly but you can not have a username or password with one character.
Second point is that the ticks suggest that you have entered a correct username and password combination which is misleading.
Perhaps the ticks should be totally removed from the sign in screen.

![screen shot 2015-05-13 at 08 01 26](https://cloud.githubusercontent.com/assets/9398950/7604692/9c626f20-f946-11e4-81ad-b8728d54722e.png)

**Comment by dragonflypl** [comment]
Good suggestion. I'll remove feedback icons. 
As for one character, I think now we don't have validation on Username in Jasify?

**Comment by krico** [comment]
We validade 3 chars on registration  i think.  But no need to validade on
signin I think
