### ISSUE TITLE
Unable to edit activity packages by clicking on the id

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#328]
Didnt know whether to label this as a bug or enhacement, but it will definitely confuse non technical users.

If I click on the activity package id I cannot edit it. But if I click on one of the other fields I can. I can guarantee some non technical users will try clicking on the id to edit the activity and will then think it doesnt work and that edit is not possible.

Can we either hide the id or make the activity package also editable by clicking on the id

**Comment by dragonflypl** [comment]
Basically all tables (after I touch them would look similar to users list, with big EDIT button). Is that approach ok ?

**Comment by pauljanes** [comment]
For me thats fine yes

**Comment by dragonflypl** [comment]
Can be closed, we have new approach for tables with EDIT buttons
