### ISSUE TITLE
Can we increase the length of the activity description by default

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#329]
Jayne wants this activity description

"No Excuses Bootcamp in Zurich is fast-paced circuit training, performing one high intensity exercise for between 30 and 60 seconds, with 30 seconds rest, before moving to another. This combines fat burning with building muscle and core strength, creating excellent all round fitness. Classes last 1 hour and no 2 classes are ever the same – which keeps them fun."

This is longer than the default length though so I have to keep enlarging the description box after it has been filled with the truncated version and then copying in the full text. If you make it longer by default this would be better.

**Comment by dragonflypl** [comment]
@krico , @pauljanes , @wszarmach 

I sent you invites to balsamiq, have a look... Anyway I was about to fix this issue, when I remembered how I wanted to create activities for the first time, and I found the form complex :) Eg I thought that Start/From dates are valid from - until....and I was wondering why it created only onc activity. Before I give a touch to this form, please have a look (and comment) and we maybe change it a bit:

![image](https://cloud.githubusercontent.com/assets/5444220/7640748/7b5f0d48-fa85-11e4-88c2-90ac1414f9df.png)

**Comment by pauljanes** [comment]
Yes Jayne also thought that you were meant to enter the date of the first activity and the last one too. Rather than it being the start datetime of the first class and the end datetime of the first class. So you are not alone Pawel

**Comment by pauljanes** [comment]
Your Balsamiq looks more user friendly than the current form.

"Repeat weekly on following days" is a bit confusing though, because you might then put Repeat every 2 weeks below that if you see what I mean.

So that should be "Repeat on following days" - removing the word "weekly"

Also what if you put a Valid to date or a certain number of occurences but then say Don't repeat. That would then seem a bit strange. I think the Valid to part needs to be down the bottom and only become enabled if the user selects Repeat weekly or Repeat on following days.

**Comment by dragonflypl** [comment]
Good point. I'll make amendments

**Comment by dragonflypl** [comment]
@pauljanes : side note: what should be max length of Activity name? I guess max length validation would be a good idea, as activity name would appear in multiple places (eg. widget) and should be short. 40 characters ?

**Comment by pauljanes** [comment]
40 seems pretty reasonable

"Jayne's morning bootcamp class Holmes Place" is 43 and that looks very long to me. Its not a real example by the way - I just wanted to see how much info you could fit in 40 chars. If you wanted to be really safe you could say 50

**Comment by wszarmach** [comment]
To check my understanding; To make an activity that starts at 23:00 and lasts 2 hours I would enter
Starts at: 23:00
Finishes at 01:00
Valid From: Today
Valid Until: Date, with date value of Today + 1 day
Is that correct?

How does "Reaches limit of X occurrences" work?

Do the days always show/are editable or only when "Repeat weekly on following days" is selected?

Can I specify that I want something to repeat until a specific date? for example every tuesday until the end of August?

"Repeat every X week/day" this is the step logic for moving to the next repeat cycle, for example for fortnightly repeats?

I wonder if the Activity Description should not be below Activity?
Price and Currency are linked fields so perhaps they should stay on the same row?

**Comment by pauljanes** [comment]
I wouldnt use that valid until date like that. For me it is only used in case of repeating activities, which is why I suggested to move it down where the rest of the repeat stuff is.

But to cover your case I think an additional field is needed - you need a start date, a start time, an end date, end time. Which is how we have it at present. Except the current labelling was confusing for jayne

**Comment by krico** [comment]
I like!  Some thoughts on future features (more to keep in mind than anything else):
 * We plan to have "Location" linked to google maps API (see #94).  You think its possible to do that integration in this sprint?
 * @pauljanes states on #208 and #353 that localization (multi-language) will be needed soon.  Should we already add the *locale* next to the description field at this point?  
 * Many of the activity fields are "auto-filled" from the ActivityType.  Do you think we should show that to the user somehow have the field with a different color if it is same as activityType or if it was changed?

**Comment by wszarmach** [comment]
I very much like the google calendar event design.
![screen shot 2015-05-15 at 23 32 12](https://cloud.githubusercontent.com/assets/9398950/7662358/b1e507ce-fb5b-11e4-837c-c1065d87e558.png)
What I like about this is;
* The activity start finish is on one line with a "to" separation making the fields purpose obvious and probably why no labels are required.
* When entering the time values there is a convenient 30 min step. The finish field adjusts in relation to the start field and shows a duration value in brackets.
* The repeat functionality is minimised and only opened for editing. Once the user has completed editing a summary line is displayed.
* The description field dynamically adjusts as you type so there is no such thing as too long a string.
* The buttons "Back, Save, Discard" are obvious (I guess we can rename Discard to Cancel).

With the exception of Price, Currency, and Capacity our screen contains the same information.

One more change I think is important is that in most systems I have seen the price and currency are on the same row.

**Comment by krico** [comment]
Good points with the google calendar.

Start+finish on same line.
Minimized repeat 

We also need to display activity type somewhere

**Comment by dragonflypl** [comment]
Ok, so many ideas :) working on it!

**Comment by dragonflypl** [comment]
Just one thought regarding minimized repeat: in jasify propably you'll in 99% repeat your activities when creating, so maybe in our case showing it at the beginning would be better?

**Comment by pauljanes** [comment]
Good point. Which is also a reason to allow a multiple edit too

**Comment by wszarmach** [comment]
Whats a multiple edit?

**Comment by pauljanes** [comment]
If you make a mistake when creating repeat activities, and then instead of editing them one by one, you want to edit the set that were created via the repeat function
