### ISSUE TITLE
May not be obvious for users how to remove something from checkout using booking-via-jasify.html

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#330]
The booking-via-jasify.html looks pretty good and is fairly intuitive for selecting activities and then you go to the checkout and you pay etc.

The thing is it wasnt so obvious for me that once I am on the checkout page, to remove something I need to go back to the activities page and deselect it. I think there will be some users who think there is no way to remove something from the checkout page unless you allow it to be removed from that page too. In others words if I deselect an activity from the activites page I would expect it to be removed from the checkout (and this already works) but on the checkout page I would like to see a way to remove the activity from my checkout (which would also deselect it on the activities page)

**Comment by dragonflypl** [comment]
Please confirm solution:

![image](https://cloud.githubusercontent.com/assets/5444220/7618390/1d643fca-f9b2-11e4-8656-4542c1061852.png)

then

![image](https://cloud.githubusercontent.com/assets/5444220/7618402/262544f6-f9b2-11e4-9006-166804a995b0.png)

**Comment by pauljanes** [comment]
The 2 images are the same no? But yes a remove option like this on the checkout screen is good. And this should also deselect it on the Activities page in iframe

**Comment by dragonflypl** [comment]
Hmm, i see different screenshots

**Comment by pauljanes** [comment]
I see
