### ISSUE TITLE
Display issue on checkout page - button cropped

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#331]
![screen shot 2015-05-13 at 14 50 35](https://cloud.githubusercontent.com/assets/9402268/7610742/7f1784b2-f97f-11e4-8198-62a4a8b5e6c5.png)

In the image all you see is Continue To Pay and then part of a letter, which I guess is a P. It seems like the button has been cropped. I am guessing it is meant to show as Continue to Paypal

**Comment by pauljanes** [comment]
Also on the activities page I see a cropping of the Create New Activity

![screen shot 2015-05-13 at 14 53 29](https://cloud.githubusercontent.com/assets/9402268/7610785/ef817d98-f97f-11e4-95d3-382e23424fc7.png)

**Comment by dragonflypl** [comment]
Checkout page fixed. Tooltip , i'll make another issue for it.
