### ISSUE TITLE
On widgets page what is at the bottom of the page - its says title and cancel and ok

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#332]
See attached screenshot. At bottom of page there is something that says Title and Cancel and Ok.

![screen shot 2015-05-13 at 14 55 29](https://cloud.githubusercontent.com/assets/9402268/7610834/51302aee-f980-11e4-90d2-33141e686067.png)

**Comment by dragonflypl** [comment]
This is bug - widget does not include styles that hide dialogs feature.

**Comment by pauljanes** [comment]
Okay. I also see the bug on https://jasify-schedule.appspot.com/booking-via-jasify.html#/O30002

**Comment by dragonflypl** [comment]
Yeap, this is the same page actually (in iframe)

2015-05-13 15:37 GMT+02:00 pauljanes <notifications@github.com>:

> Okay. I also see the bug on
> https://jasify-schedule.appspot.com/booking-via-jasify.html#/O30002
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krico/jas/issues/332#issuecomment-101665413>.
>



-- 
Pozdrawiam
Paweł Waszczyński

**Comment by dragonflypl** [comment]
Done
