### ISSUE TITLE
On some of the screens I see a Reset button - is this to Cancel?

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#333]
I see on several pages a Reset button. Thinking from a non-technical user point of view, would this be better as Cancel? As users we are used to seeing Save and Cancel (or OK and Cancel). Reset we are more used to seeing when we revert to some factory state. eg reset iphone.

Does it serve the same purpose as a cancel? If so then I think it is better to name it cancel. But perhaps I am wrong and it is not equivalent to a cancel?

**Comment by pauljanes** [comment]
Check out this article where Nielsen (who are very well respected) talk about reset and cancel buttons and usability advice http://www.nngroup.com/articles/reset-and-cancel-buttons/

**Comment by dragonflypl** [comment]
Which screens do you mean? Screenshots?

**Comment by pauljanes** [comment]
In general - all the screens where there is a Reset button. I am not sure users will understand what the Reset button does.

Cancel seems better

**Comment by dragonflypl** [comment]
OK. Will read this article.

2015-05-13 15:31 GMT+02:00 pauljanes <notifications@github.com>:

> In general - all the screens where there is a Reset button. I am not sure
> users will understand what the Reset button does.
>
> Cancel seems better
>
> Sent from my iPhone
>
> > On 13.05.2015, at 15:29, "Paweł" <notifications@github.com> wrote:
> >
> > Which screens do you mean? Screenshots?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krico/jas/issues/333#issuecomment-101664281>.
>



-- 
Pozdrawiam
Paweł Waszczyński

**Comment by krico** [comment]
What the reset button does in this case (and I have nothing against changing it to cancel) is reset the entity to it's original state.  So user continues to edit but undoes changes that weren't saved.

**Comment by pauljanes** [comment]
Ah ok. That wasnt clear for me, so I think better to just have a cancel option. For instance people could expect that a Reset button would reset something to its "factory default" rather than the last save.

**Comment by wszarmach** [comment]
Maybe " Undo" rather than "Reset"?

**Comment by pauljanes** [comment]
What I dont understand is why you wouldnt just cancel the action. This is what the article is about. There is little reason to reset/undo when you have the abiliy to cancel and try it again if necessary

**Comment by wszarmach** [comment]
Had not read the article when I wrote my comment. Have nothing against Cancel (or back as the article suggests)
