### ISSUE TITLE
PaymentWorkflow cancelation task needs to check PayPal before canceling

### ISSUE THREAD

**Issue by krico** [krico/jas#338]
If the following scenario (one of infinite possibilities):

 1. User goes to checkout and clicks "Continue to Pay Pal"
 2. User authenticates on PayPal 
 3. User accepts the payment
 4. The user's 3 year old daughter who is running after the newly acquired baby cat with a "Princess Elsa of Arindel" costume holding a Darth Vader light sabre and screaming "Let it goooo, let it gooo!" trips on the "Buzz Lighyear" figure that was forgotten there by the user's 6 year old son.  As she is falling down, Buzz Lightyear figure says "I am Buzzzz lightyear, at your service".  She falls on top of the sleeping golden retriever, the dog barks and jumps and with his jump he **rips of the power cable of the wifi router**.
 5. User closes his laptop to attend to his crying daughter, calm his dog, save the baby cat, power up the wifi router and yell at his son for leaving Buzz on the floor.
 6. User opens his laptop and is presented with "Connection Interrupted"

Now PayPal thinks the user has paid, but Jasify never got notified of this.  So the Cancelation task should actually "confirm" the payment in this case, rather then cancel the subscriptions.

**Comment by pauljanes** [comment]
How do you know if they paid in this case, if jasify did not get the confirmation from paypal?

**Comment by wszarmach** [comment]
Why would Jasify not be notified due to a front end issue?
