### ISSUE TITLE
New Jasify Version requires frontend refresh

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#343]
When a new release is made with frontend changes end users that have not refreshed their browser dont necessarily see the changes due to browser caching. We need a way to force a browser refresh.

**Comment by dragonflypl** [comment]
@krico : there's a new task 'build-prod' that does the thing:

```javascript
gulp.task('build-prod', function(callback) {
   runSequence('clean', 'build', 'rev', callback);
});
```
