### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#353]
We will have problems getting some providers onto jasify if we cannot offer multi language support. Jayne does all her classes in english, but some of the other gyms interested in jasify have mainly german speaking clients.

So all the menus etc need to be available in german and english (and later french). Also mywayfit should be able to indicate the language when the booking link is clicked so that the user seamlessly goes from a german version of mywayfit to a german version of jasify for instance.

It will be up to the provider to enter the activity description in whatever language they want it to appear in. This part will not be translated. But all the menu items should be.

mywayfit is already translated in english, german and french.

**Comment by krico** [comment]
relates to #208

**Comment by wszarmach** [comment]
Replaced by #461
