### ISSUE TITLE
When using book it url and payment is not completed, the place is not released after 30 mins

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#361]
Yesterday I started to book a class via mywayfit using the book it url and then abandoned part way through, meaning that I had not paid. But I still managed to keep my place even after the 30 minute period (when it is then meant to be cancelled).

This is a blocker for allowing Jaynes classes to be booked via mywayfit as she only wants people that have paid to get a place in her classes. And as mentioned to Waldemar I am running a facebook ad campaign at the moment taking people directly to the page where they can book metafit classes.

**Comment by wszarmach** [comment]
Already fixed
