### ISSUE TITLE
Errors when I add widget code to a html file. Missing " and local path used to booking-via-jasify.html

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#364]
I created the following by copying and pasting the widget code into a html file:

<html>
<head>
<meta charset="UTF-8">
<title>No Excuses - Embedded iframe</title>
</head>

<body>

<div id="booking-via-jasify></div>

<script id="booking-with-jasify-script" src="https://jasify-schedule.appspot.com/booking-via-jasify.js?organizationId=O30002"></script>

<script src="https://jasify-schedule.appspot.com/build/js/dep-iframeresizer.js"></script>

<script>
    window.createBookingViaJasify();
    iFrameResize();
</script>
</body>
</html>

I noticed that the page was blank and the first problem I see is that in the widget code there is a missing " after the div id. It should be <div id="booking-via-jasify"></div> instead of <div id="booking-via-jasify></div>

Now that I manually edited the code to add the missing " I still get an error though. See screenshot below.
![screen shot 2015-05-17 at 16 09 19](https://cloud.githubusercontent.com/assets/9402268/7670702/43f8dad8-fcaf-11e4-8acf-403b67130776.png)

**Comment by pauljanes** [comment]
Ok I looked in the js file and I see this

ifrm.setAttribute("src", "booking-via-jasify.html#/" + queryParams.organizationId);

That looks suspicious to me as it seems to be a local path, meaning it wouldnt work from mywayfit.ch, oder?

**Comment by dragonflypl** [comment]
it should have application domain before it:

https://jasify-schedule.appspot.com/booking-via-jasify.html
