### ISSUE TITLE
Add user shows Showing 1 to NaN of 45 entries and search is case sensitive

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#367]
I saw "Showing 1 to NaN of 45 entries" when the search does not return any results. NaN the average user will have no clue what this means :) And actually it is not showing 1 to NaN as there are zero results.

Do you want the search to be case sensitive? I searched for Paul and found nothing, but when I scrolled through users I saw all my user names are lower case. Do you think it would be better to make the search case insensitive? If not then we can at least include a checkbox that says Case insensitive that the user can tick if they are not concerned with case.

**Comment by wszarmach** [comment]
I think it makes sense to make the search case insensitive. I also had trouble finding myself

**Comment by pauljanes** [comment]
You can see the above using the link https://jasify-schedule.appspot.com/#/admin/activities/A720001-O30002/subscribe

Then just type "Paul" and hit search and you will see the "Showing 1 to NaN of 45 entries"

**Comment by wszarmach** [comment]
Replaced by #371 and #372
