### ISSUE TITLE
Investigate and delete activity packages AP950004-O30002, AP870002-O30002 and AP840002-O30002

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#374]
Activity packages AP950004-O30002, AP870002-O30002 and AP840002-O30002 seem to be screwed. Jayne asked me to create one activity type per location so I had to delete the old activities. Somehow this screwed the activity packages. I guess there are dangling references.

Since the client can see any APs that exist, we need to delete activity packages AP950004-O30002, AP870002-O30002 and AP840002-O30002 from the database.

Do not delete the other 2 APs that I created.

**Comment by pauljanes** [comment]
You can see the APs mentioned above at https://jasify-schedule.appspot.com/#/admin/activity-packages/O30002

**Comment by krico** [comment]
We fixed this in prod
