### ISSUE TITLE
Widget on page not fully visible

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#379]
I embedded the widget code for No Excuses Zurich on mywayfit at www.mywayfit.ch/noexcuses.html but I can only see the top part of the iframe.

See screenshot below. Is there something special that is meant to be done in order to make it fully visible?

![screen shot 2015-05-18 at 22 10 27](https://cloud.githubusercontent.com/assets/9402268/7689205/df602d68-fdaa-11e4-9585-a95b7a12dfc7.png)

**Comment by dragonflypl** [comment]
@krico  is on it.
