### ISSUE TITLE
Widget Iframe doesnt seem to load on iphone 5

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#382]
I have copied the widget code to www.mywayfit.ch/noexcuses.html and on my mac using chrome it works fine. But on my iphone it doesnt load. And chris just said it doesnt work on firefox either

**Comment by dragonflypl** [comment]
Will check it. Could be something with site+browser security as widget works on FF from https://jasify-schedule.appspot.com/#/widgets

**Comment by krico** [comment]
@pauljanes could you please do a quick test for me, go into [Jasify](https://jasify-schedule.appspot.com) and login, then go back to [noexcuses](http://mywayfit.ch/noexcuses.html).

I suspect the widget doesn't work with unauthenticated users.

**Comment by pauljanes** [comment]
Tried that. Am logged in to jasify. But the noexcuses.html is still blank. The symbol to show its loading in browser keeps spinning and spinning but nothing displays

**Comment by dragonflypl** [comment]
I confirm issue is for not auth users

**Comment by dragonflypl** [comment]
@krico Could you have a look at the screenshot? What i'm doing wrong in the widget?

![image](https://cloud.githubusercontent.com/assets/5444220/7707011/0df9ab2e-fe4e-11e4-840c-ccf008f82e93.png)

**Comment by dragonflypl** [comment]
Is it because: return Allow.adminOrOrgMember()  in resolves ?

**Comment by krico** [comment]
`Auth.restore()` "fails" when you are not logged in.  So yes, probably

**Comment by krico** [comment]
It should be `Allow.all()`
