### ISSUE TITLE
Jasify layout doesn't work on IE9

### ISSUE THREAD

**Issue by krico** [krico/jas#385]
![image](https://cloud.githubusercontent.com/assets/6952185/7705826/e706f2f8-fe46-11e4-849b-b6702940bc5b.png)

**Comment by dragonflypl** [comment]
When I started I asked about browsers to support , we decided to go with Last Version - 1 (eg IE11, IE10). For IE9 and earlier there's an issue:

https://github.com/krico/jas/issues/259

**Comment by krico** [comment]
Notification would be better, but I thought we said we support what angular 1.3.x supports.  I might be wrong, but I think they support IE9, don't they?

**Comment by dragonflypl** [comment]
Angular supports it , but eg. angular material and many other css components drop IE9, and stick to N-1 support

**Comment by krico** [comment]
OK, if there is no "easy" way around it (eg: shim/shiv) and we add the notification, just close this issue.

**Comment by dragonflypl** [comment]
Done
