### ISSUE TITLE
Paypal checkout hangs forever

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#387]
Tried out the widget via mywayfit.ch/noexcuses.html on Mac/ Chrome

Added an activity to checkout then clicked Continue to Paypal but then it hangs forever (see screenshot). It did not ask me to authenticate yet in case that matters to your investigation.

![screen shot 2015-05-19 at 21 26 42](https://cloud.githubusercontent.com/assets/9402268/7711916/2a082780-fe6e-11e4-865e-f8119dbaf51a.png)

**Comment by pauljanes** [comment]
I still see this issue this morning, and I see there was a release at 03.04am. If this change went into that release then it appears that it doesnt work. Still get the hanging screen when I click Continue to Paypal.

**Comment by pauljanes** [comment]
Tried closing everything and repeating. This time instead of hanging forever I get Failed: Service Unavailable upon hitting the Continue To Paypal button. See screenshot below

![screen shot 2015-05-20 at 07 50 32](https://cloud.githubusercontent.com/assets/9402268/7719753/20e9dc46-fec5-11e4-93f1-67bcecd2a886.png)

**Comment by krico** [comment]
This second failure is because you are already subscribed to some of the activities probably...

**Comment by pauljanes** [comment]
?

**Comment by pauljanes** [comment]
No, its definitely broken. Just tried it again now with different activity. Cant get past the continue to paypal part. And according to jasify i am not subscribed to any activities. Plus i have not paid a dime to my paypal account. At the moment it seems i have no way to book and pay for an activity end to end

**Comment by pauljanes** [comment]
![screen shot 2015-05-20 at 23 12 13](https://cloud.githubusercontent.com/assets/9402268/7736672/cac8f2f8-ff45-11e4-8e9e-22884427e068.png)

**Comment by krico** [comment]
Here's some information about [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options)

**Comment by pauljanes** [comment]
Refused to display 'https://www.paypal.com/ch/cgi-bin/merchantpaymentweb?cmd=_flow&SESSION=ZFk6…e0b7e69bf0224adecfb0124e9b61f737ba21b08198acc59b45c1b5383c3fbf91319c9514c0'

**Comment by krico** [comment]
closed with #401
