### ISSUE TITLE
Widget - Empty checkout on iphone / safari even though I selected an Activity

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#390]
Using widget on mywayfit.ch/noexcuses.html on my iphone 5 with safari

I selected an Activity then went to the Checkout. But I do not see any items in the Checkout. All I see is an info message saying that "Booking is done via Jasify......". Then below that a Sign In box and below that a Create Account box. And below that nothing. I should see the item in the Checkout that I selected. On my mac with Chrome it works and I do see the activity that I selected in the Checkout.

**Comment by dragonflypl** [comment]
Done
