### ISSUE TITLE
Stuck on checkout after pressing Submit button on iphone 5 / safari

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#394]
I used the widget on mywayfit, selected an activity, went to checkout, signed in with facebook and was authenticated. Now I have the checkout showing my one item and a button to Submit.

But when I hit Submit on the checkout, the shopping trolley spins and then nothing more happens. It seems like it is stuck or as if an error has occurred on the backend that prevents it going any further.

**Comment by krico** [comment]
Paul, was this after the last release?

**Comment by pauljanes** [comment]
Yes

**Comment by krico** [comment]
closed with #401
