### ISSUE TITLE
For consistency the subscriber should be able to tick select APs in widget just like he can tick select an activity

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#395]
On the Activities tab the subscriber can select any activities he wants by putting a tick next to them. See screenshot below.

But on the APs screen it is not consistent as the subscriber has to go inside the AP and select eg 11 of 11 activities. I think we should have a tick select next to the AP itself. And then since you are making the user select 11 of 11 at present, if the user ticks the box next to the AP you can auto select the 11 activities and disable them from being deselected. In a later stage you can make it more flexible by allowing him to select eg 10 of 11. But for now I think it would be a major improvement just to put a tickbox next to the AP and to autoselect the 11 activities and prevent them from being deselected. 

As a user it would drive me a bit crazy having to tick 11 activities 1 by 1 when it is the only option I have in order to continue. I would be wondering why the system does not autoselect them if I must choose 11 of 11.

![screen shot 2015-05-20 at 08 02 57](https://cloud.githubusercontent.com/assets/9402268/7719927/332bc20a-fec7-11e4-905b-f22a696b07e0.png)

**Comment by dragonflypl** [comment]
Done
