### ISSUE TITLE
Activities on widget must be date sorted - currently they are not

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#396]
If you look at the screenshot below, the activities that can be booked individually are not date sorted. This makes it almost impossible to find the activity you want to book. We need them to be sorted in date order, and we should not show the activities that have already elapsed. Jayne picked up on this right away when she looked at the widget.

![screen shot 2015-05-20 at 13 19 00](https://cloud.githubusercontent.com/assets/9402268/7724604/314bfdb6-fef3-11e4-9540-fbddf942bc70.png)

**Comment by wszarmach** [comment]
restricting the expired activities should be done by sending in current datetime in the from field in the query. Similar to #321
