### ISSUE TITLE
Make sure that activitity packages are not shown in widget if the end date of the last activity in that AP has passed

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#397]
Each month users will subscribe to APs, meaning they can no longer be deleted. So we need to make sure that in the widget we do not show the APs to user if the date of the last activity in that AP has passed. Similar to the fact that we should not show Activities in the Activities page of the widget if the date of that activity is the past.

The difference between Activities and APs is that we dont need to show individual activities in the Activities page once the activity date has passed. But with APs we should continue to show them until the date of the LAST activity in that AP has passed (or we can stop showing them before that if we figure out that it is no longer a good deal for the client eg he is better off to purchase them individually than with an AP). For now I prefer the simplest approach which is to keep showing APs until the date of the last activity in the AP has passed.

**Comment by wszarmach** [comment]
Suggestion; this could be controlled via the ap valid until field. To start with if the org admin doesnt set this the backend could fill it.

**Comment by pauljanes** [comment]
Ok

**Comment by pauljanes** [comment]
Probably better to name it something that the provider knows how it is being used though

Eg Stop selling to clients on <date>

**Comment by wszarmach** [comment]
on the front end we can change the name to suit, this is the query field

**Comment by dragonflypl** [comment]
@wszarmach so are we going to have additional field or should I analyze activities?

**Comment by wszarmach** [comment]
the ap has two time fields valid from and valid until but they are currently not being used

**Comment by dragonflypl** [comment]
@pauljanes : question, should this Valid Until field me mandatory?

**Comment by pauljanes** [comment]
I think that provider should not have to set it. But if they dont set it then system should set it

**Comment by dragonflypl** [comment]
And set it to which value?

**Comment by pauljanes** [comment]
Start date of the last activity in the package would make sense for now. After the last activity in the AP has started the AP has no monetary value to the user

In a later stage Chris and Waldemar were talking about trying to determine when it is better for user to buy the individual activities instead of the AP. But until then, the solution I suggested is fine
