### ISSUE TITLE
Widget PayPal checkout is blocked because of X-Frame-Options: SAMEORIGIN

### ISSUE THREAD

**Issue by krico** [krico/jas#399]
The PayPal checkout sets the header  

[X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options): SAMEORIGIN

 as a protection against click-jacking.  Unfortunately this means the current checkout mechanism will **not work** on the Jasify Widget.

What this means effectively is that we cannot perform the PayPal checkout inside of an iframe so we are left with two options that I can think of

 1. Open a popup window (we had problems with this on iphone)
 2. redirect the parent window (take over the web page) to paypal

I will try to go with option 2. to avoid having problems on mobile devices.
I also suspect this is should also close #387 and resolve #394

**Comment by krico** [comment]
I found this [bug report](https://code.google.com/p/chromium/issues/detail?id=136610&q=window.opener&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20OS%20Area%20Feature%20Status%20Owner%20Summary) that explains why the popup doesn't work on iphone (mobile in general) especially with chrome.  And I also found [this workaround](http://stackoverflow.com/questions/14637937/window-opener-not-set-in-ios-chrome) that proposes opening the new window with 
```javascript
win = window.open(paypalURL,'_blank');
```
 so I'm actually going to try option 1.

**Comment by pauljanes** [comment]
Ok. When we had those problems with facebook auth on mobile, I was using safari as my browser just so you know.
