### ISSUE TITLE
Activity.description textbox should be bigger or auto-resize

### ISSUE THREAD

**Issue by krico** [krico/jas#402]
![image](https://cloud.githubusercontent.com/assets/6952185/7761823/58964b5e-002b-11e5-93f8-020d6e04447b.png)

**Comment by dragonflypl** [comment]
THere's an autosize plugin which works on IE,FF,GC on Win:

![image](https://cloud.githubusercontent.com/assets/5444220/7765650/bbd3d300-0060-11e5-890f-67d55b3a5804.png)

I'll check it
