### ISSUE TITLE
Should the activity buttons really use two lines when the width is reduced?

### ISSUE THREAD

**Issue by krico** [krico/jas#403]
Is this intentional?  Using full screen I see
![image](https://cloud.githubusercontent.com/assets/6952185/7761846/b229ff4e-002b-11e5-9ab2-78eb1a386d84.png)

And if I reduce it a little bit in width I get:
![image](https://cloud.githubusercontent.com/assets/6952185/7761875/eef3afce-002b-11e5-9e72-912a87712bb4.png)

**Comment by dragonflypl** [comment]
Nope. it should not be like this, at least no on md/lg screen sizes. This is fixed now.
