### ISSUE TITLE
Feedback from Jayne 24th May 2015

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#415]
Jayne doesnt want to go live in June because of the issues below and the fact we havent thorougly tested the system and got it stable yet. Can we address these points asap. I cannot afford to not go live in July because we need at least one gym using our system with all of their clients to persuade others onboard. And we cant monetise until we are out of the beta phase.

Jaynes mail:

Hey,
Sorry I was out all day yesterday.
 
Please see your receipt below the time stated for the class is wrong?
It says 05.00-06.00. I presume only you can change the price to 1CHF?!
 
Then just a few small things, but before we let my lot lose on it I want things to be right.
 
It’s on my website but takes forever to load, is that me?
 
It asks that people have read the GTC (which they will as they have to tick it) but the GTC are still the mocked up ones.
 
It says cancel and return to My Way Fit it needs to say return to No Excuses.
 
Once I got to go back I couldn’t then add additional classes? I’ve tried to send you a screen shot of this but it won’t load.
 
Can we agree a few terms and conditions before payment starts going to you?!
 
Thanks,
Jayne.

**Comment by wszarmach** [comment]
The time issue should be fixed
GTC is fixed
