### ISSUE TITLE
Widget - more buttons needed for navigation between pages. Current solution assumes users are a little bit technical in nature.

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#416]
Jayne has asked for, and it makes sense, back buttons from the checkout to the activities and activity packages pages. We cannot expect non technical users to know that they can click the tabs.

All the following should be possible via buttons:
From the activities page you should be able to continue or go direct to to checkout
From the activities packages page you should be able to go back or go to checkout
From the checkout page you should be able to go back to activities or to activity packages

![screen shot 2015-05-24 at 13 43 09](https://cloud.githubusercontent.com/assets/9402268/7787722/15ea9e4e-021b-11e5-9ec8-68722aa47d08.png)

**Comment by pauljanes** [comment]
It looks better now. But why cant user go direct to Checkout from the Activities page? Some users will only be interested in single activities and then will want to go direct to Checkout (skipping step 2). Can we add this too.

**Comment by pauljanes** [comment]
This screen should also allow user to go directly to the checkout. So they should be able to go either from step 1 directly to step 3, or from step 1 to step 2

![screen shot 2015-05-29 at 15 37 31](https://cloud.githubusercontent.com/assets/9402268/7883707/c6131674-0618-11e5-9deb-652776b3a8d9.png)

**Comment by pauljanes** [comment]
This screen should have a Back option

![screen shot 2015-05-29 at 15 40 37](https://cloud.githubusercontent.com/assets/9402268/7883744/1dc69e86-0619-11e5-9da1-c32c31dd8390.png)

**Comment by dragonflypl** [comment]
Task done. Please review after release and close it if ok.

**Comment by pauljanes** [comment]
I reviewed and it looks pretty good now except I see no back buttons on the pre authenticated checkout screen. I raised issue #533 for this

**Comment by dragonflypl** [comment]
#533 Closed
