### ISSUE TITLE
Investigate if widget page can be loaded faster. Current response time is slow

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#417]
Jayne commented on how slow the widget loads on her site at http://www.noexcuseszurich.com/#!pay-for-your-course/cwtx

I also noticed the same from mywayfit. It can take between 5 and 10 seconds before you see the widget appear.

I know there is a bit of to and fro between the site where the page is embedded and jasify to get the latest info. But is there a way to speed it up? Or to at least show a message that page is being loaded or something? Ideally the former.

**Comment by dragonflypl** [comment]
From what i see, at least in Poland, fetching activity package activities takes too long. There are two requests : activity-packages-activity/AP1250002-O30002 & activity-packages-activity/AP1110003-O30002 and each takes ~2seconds

**Comment by wszarmach** [comment]
improved sufficiently wwith last changes

**Comment by wszarmach** [comment]
Linked to #487
