### ISSUE TITLE
No activites are defined for No Excuses shows briefly to user and should be removed

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#422]
When I go to the Activities screen and select org No Excuses, until the activities are loaded it shows the message "No activities are defined for No Excuses". See screenshot below. This is bad because if the user is not patient they might think our system is broken. We should only display the message No activities are defined for .... if there really are not activities defined. In this case the message is false and should either be removed or should say Loading activities for ...

![screen shot 2015-05-24 at 14 17 27](https://cloud.githubusercontent.com/assets/9402268/7787815/a79b0b04-021f-11e5-9171-2191429c6c84.png)

**Comment by dragonflypl** [comment]
This one was already fixed.
