### ISSUE TITLE
On the main organisation page, "Users" should be renamed to "Administrators"

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#433]
In the screenshot what you are calling "Users" are actually "Administrators".

This is important because we should also have users, where we add any users that have previously subscribed to any of this organisations' activities.

![screen shot 2015-05-25 at 10 29 00](https://cloud.githubusercontent.com/assets/9402268/7794288/f89bd7b4-02c8-11e5-93f1-f317e0d57d37.png)

**Comment by wszarmach** [comment]
That is not the intention of that field. For the time being we are abusing this to specify org admins but the correct setup would be to use groups.

**Comment by wszarmach** [comment]
Nothing to change
