### ISSUE TITLE
Feedback from Strictly Fitter

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#447]
Hi Paul... here goes:

I've entered all my classes and availability up until mid July when the courses end for the summer.
I will start again week of August 10th.

The difficulties or errors I found were as follows:
1. Doesn't work from Microsoft internet explorer. Only works from firefox.
2. Typo on THU Box. It says TRU.
3. Down scroll bar on activities page does not work.
4. For the last date of the course to appear on the schedule, you need to go one week beyond the final class. This is a bit annoying. You have to enter an imaginary date where you are not teaching and already finished.

Please can you make these live and let me know where we go from here?

Thank you and have a nice evening....

**Comment by wszarmach** [comment]
1. Raised in separate issue #35 
2. This was referring to the repeat on days field were Thursday was represented as THU. Fixed
3. There is no scroll bar is this perhaps a Firefox issue?
4. Investigating
