### ISSUE TITLE
On mywayfit I need the ability to search multiple activity types in one query

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#453]
At the beginning, Chris provided me with the query below that I can run from mywayfit. The thing now is that for Bootcamp for instance, I now have 3 separate activity type ids (Jayne's morning bootcamp, Jayne's evening bootcamp and Sonya's bootcamp). And I need that the mywayfit user can click "Bootcamp" and then see all of these results together in one query. I need a way that I can provide the query with multiple activity ids. Can you please tell me how to do this or can you change the backend to support this.

	gapi.client.jasify.activities.query({
		partner: "mywayfit.com",
		activityTypeId: activityTypes[i], // I need to be able to pass multiple activity type ids here
		fromDate: (new Date(Date.parse(document.getElementById("fromdate").value))).toISOString(),
		toDate: (new Date(Date.parse(document.getElementById("todate").value))).toISOString(),
		limit: 0,
		offset: 0
	}).execute(responseHandler /* function below */);

**Comment by wszarmach** [comment]
See also #351 and #352

**Comment by pauljanes** [comment]
I am now passing an array into the activityTypeId field, but presently I get back only the results from the first element of the array
