### ISSUE TITLE
User feedback: user was confused by the add activity type screen via Admin - Organizations

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#466]
The old way of adding new activity types needs to be removed. The old way of adding activity types is still available via Admin - Organizations. There is a table of existing activity types with a + option. See screenshot below. But this table should be removed because 1) via this way there is no validation of the activity type fields when creating a new activity type, and so the user was trying to enter prices with non numeric chars (see screenshot) but not getting any feedback as to why the Save could not be done 2) it is not possible to edit the entries in this table.

Users should only be able to enter the activity types via the new way with an edit option, and validation of the fields etc
![screen shot 2015-05-29 at 15 45 03](https://cloud.githubusercontent.com/assets/9402268/7883930/90b91576-061a-11e5-9d97-9dfc010ca5a6.png)

![screen shot 2015-05-29 at 15 45 03](https://cloud.githubusercontent.com/assets/9402268/7883850/dc6f5490-0619-11e5-8cb6-222bf65782d2.png)

**Comment by wszarmach** [comment]
The old activity type screen will be removed.

**Comment by wszarmach** [comment]
Which user gave this feedback and were you demonstrating the gui with your login or the users?

**Comment by pauljanes** [comment]
The owner of ZeoT. She was trying to add new activity types herself with her own login. I wasnt with her - she sent me mail telling me system wouldnt let her save her new activity. When i saw screenshot it was because she had (.... Student) in price field. But field did not show validation error - so it must have been accessed via table
