### ISSUE TITLE
More user feedback from ZeoT - we definitely need to confirm deletes

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#470]
The owner of ZeoT deleted by accident one of the activity types. We definitely need to make sure that deletes are confirmed. I already thought people might accidentally click on delete and this mail confirms it to be the case. When someone clicks delete we need to pop up a message "Are you sure you want to delete...."

From: alia mckenzie-murdoch <yallaalia@gmail.com>
Date: 30. Mai 2015 15:50:27 MESZ
To: MyWayFit <paul@mywayfit.com>
Subject: Re: Your sms - contact via Jayne Salmon

Hi again!!!

I don't normally have problems doing things like this...but somehow your system and I are not getting along very well. I thought I had added a class but when I searched for belly dance classes afterwards on the site, there were no search results!
I also managed to delete the dance fit activity you created for me!

Could you add these dates/times? and then maybe you will have to show me again some time how it works! sorry for this!!!

Thanks for your help!
Best wishes,
alia

**Comment by wszarmach** [comment]
I tried to delete an activity type and got a "Are you sure?" popup.
I tried to delete an activity and got a "Are you sure?" popup.
Evidence below. Not sure what more can be done.
![screen shot 2015-05-30 at 22 42 42](https://cloud.githubusercontent.com/assets/9398950/7899277/4732a742-071d-11e5-9984-c1527a1f4b21.png)
![screen shot 2015-05-30 at 22 42 54](https://cloud.githubusercontent.com/assets/9398950/7899278/4b86d606-071d-11e5-8b61-17d6959ddc0c.png)

**Comment by pauljanes** [comment]
If she also got that then yes seems there is not more to be done. But if you saw feedback it gives the impression she accidentally deleted it. I was not there with her so all I can do is pass on the feedback I got.

**Comment by pauljanes** [comment]
You are deleting the activity type from the new screen though by the way. The one that you said is not visible to org administrators.

**Comment by pauljanes** [comment]
I just tried it from the old way in the table i.e. the one that the org admin see. And there you can delete an activity type with no confirmation required. So the test you did is not the same as the view she has. But what your test does at least prove is that when you remove the old way and give org admin the new way this issue will then be fixed.

**Comment by wszarmach** [comment]
Will be closed by #466
