### ISSUE TITLE
Focus for the coming days

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#487]
We are in a good position to go live with Jayne in July if:

1) #418 is fixed so that there are no references to MyWayFit when users enter via her website
2) booking and payment works on both mobile and non mobile devices - including facebook and google signins (which Chris said he would need to change behaviour to add popups in case user is not signed in to facebook or google). And it needs to work without the user having to allow all cookies, which is the current state of affairs. We should also display a prominent message saying that the site uses cookies and will not work properly without them #421
3) In case of unsupported browsers we need to display a message telling the user that their browser is unsupported and telling them they need to update it #385
4) speed of widget loading needs to be improved as especially on mobiles it is painfully slow #417
5) pawel to add in a couple of extra navigation buttons eg from activities step 1 direct to checkout, and from the checkout basket an option to go back #416

We should place precedence on all of the above over adding in nice-to-have stuff. General improvements etc that have no impact on Jayne or the end user should wait until later.

We do not want to lose yet another month because of failing to solve the above.

**Comment by wszarmach** [comment]
Also #489

**Comment by dragonflypl** [comment]
#416 Done. Please review

**Comment by pauljanes** [comment]
#418 seems one of the most urgent and seems like a quick to do. Because Jayne doesnt want her clients to see any reference to MyWayFit where they could find other providers. Although it doesnt actually direct there, after seeing the name MyWayFit, her clients might google the name. Can we knock this off the list asap.

**Comment by dragonflypl** [comment]
#385 Done.

**Comment by pauljanes** [comment]
These need to be closed before Wednesday 24th June ie in 2 days time because Jayne is sending a mail to ALL her clients on Wednesday morning telling them to book via jasify.

**Comment by wszarmach** [comment]
#417 done
