### ISSUE TITLE
Activity Date is shown in US format

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#501]
I started to create a new activity and noticed that the 1st of July is shown as 7/1/2015.
![screen shot 2015-06-09 at 00 39 36](https://cloud.githubusercontent.com/assets/9398950/8046992/272abf32-0e40-11e5-93a0-d4573f76ec89.png)

This does not appear to be the case in the current production version so its due to a recent change. Maybe locale related?

**Comment by dragonflypl** [comment]
Yes, this is because now on Profile you can select en/de . Unless selected, it defaults to en . Also I'm waiting for #495 to fully complete locale task.

**Comment by dragonflypl** [comment]
Also this is code that sets default language:

``` javascript
        if (navigator.languages && navigator.languages[0]) {
            defaultLocale = navigator.languages[0];
        } else if (navigator.language) {
            defaultLocale = navigator.language;
        } else {
            defaultLocale = 'en';
        }
```

so my guess is that you browser return en (you can check it in console)

**Comment by wszarmach** [comment]
Ok. this is my bad. My default locale is set to "en-US" and the US part is what is causing the date format.
