### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by dragonflypl** [krico/jas#505]
@krico @wszarmach @pauljanes 

I would like to redesign login page, no dialog (is it a bit annoying that you have to make at least three clicks to log in even though you're **returning** user, don't you think?) and more like Strava.com style + i'll pick some photos from shutterstock . 

To make it easier to create I would put it into separate login.html, why?
- we could cut down on css,javascript we include on login page in the future so it loads faster (and other scripts are downloading in the background). Basically login page whould be ultra lightweight
- index.html has a lot of plumbing code ```isAuthenticated()``` etc... that creates many unnecessary watches and litters controllers & html . We could clean up index.html and js controllers of this code . 

What do you think?

Estimation: 1h.

**Comment by wszarmach** [comment]
Would this also change the sign in / sign up for the widget?

**Comment by krico** [comment]
:+1:  would simplify a lot!

 * How would we handle the "unauthenticated"  access that we have right now?  For example, if I saved a URL to #/admin/whatever/123 and click on it, would we jump to index.html and save the path for post-login?
 * What would we use as return-url for OAuth login (Facebook, Google), would that still go over index.html?

**Comment by dragonflypl** [comment]
- initially it won't affect widget. If you like it , we can replace widget logging as well
@krico 
- yes. We need event that will be raised when user is not authenticated. I guess we already have it?
- yes

**Comment by dragonflypl** [comment]
Here's proposal:

![image](https://cloud.githubusercontent.com/assets/5444220/8086191/61cb9634-0f94-11e5-9225-1895125dd41c.png)

**Comment by krico** [comment]
:+1: I like!  Is that a free image?

I need to change widget a bit to resolve X-Frame-Origin: DENY (#410) problem.  So please keep me posted on what areas/modules you are changing so that we don't have conflicting changes...

**Comment by pauljanes** [comment]
Yes image was ok with me.

Shutterstock is not free but for 12chf or so u have rights to the image to use on a commercial site.

**Comment by wszarmach** [comment]
+1 for me too. I like

**Comment by dragonflypl** [comment]
@krico  : I'll have time over the weekend to do it (propably on sunday) so I'll get it touch with you if there's a brach i could rebase to in order to avoid conflicts.

**Comment by dragonflypl** [comment]
@pauljanes : any feedback on login page? Can we close this issue ?

**Comment by pauljanes** [comment]
Yes login page is fine now
