### ISSUE TITLE
Feedback from Jayne 22nd June

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#537]
Clicking add activity with her user info@noexcuseszurich.com causes the + icon to spin but 9 times out of 10 does not appear to do anything. The one time she got the screen to appear she mentioned that the Save and Cancel buttons should be at the bottom of the screen, rather than having to scroll around the page to find them. And when there is an error the focus should go to that field because the repeat every x weeks was not filled in, but she did not know that till I told her to scroll around page and see if there were any fields highlighted in red.

**Comment by pauljanes** [comment]
I checked and she is using Chrome. I also use Chrome and when I use the user info@noexcuseszurich.com I was getting the New Activity screen ok. Do you have logs that you can check to see if there are errors from the times when she clicks on Add Activity and it doesnt work? Under what scenarios would the icon spin but nothing happen? Could this be some kind of timeout that is not properly handled? She tried clicking refresh but still the + icon span but the New Activity screen did not come. This one is obviously a major bug as she wasnt able to add her classes and I had to do it for her.

**Comment by pauljanes** [comment]
Jayne asked that the tick next to the AP says Select All/ Deselect All. It was not clear to her that once it was ticked if she unticked it that it would deselect all. She thought she had to deselect all the activities one by one.

![screen shot 2015-06-22 at 21 48 27](https://cloud.githubusercontent.com/assets/9402268/8291241/8d4358c2-1928-11e5-8751-5894e824a607.png)

**Comment by pauljanes** [comment]
She also wants an option that she can create activities and activity packages that the user cannot yet see on her site. So for instance she would create all the Bootcamp classes for August, but they would be invisible to the user till a certain date that she defines. Similar to the way that we did an activity package valid Till date. Except for that here it would be a valid From date and would be applied to Activites and Activity Packages.

**Comment by dragonflypl** [comment]
1. Save & Cancel at the bottom - done, although from UX point of view + IMHO this is bad idea. If user's screen won't accomodate whole page, when accessing the page user won't see Save/Cancel. It will be even worse on touch devices. Also it seems wierd that uses is searching for Save/Cancel button if these buttons are visible at the glance when page is loaded. 

2. Scroll & focus to invalid form field on submit - done

**Comment by dragonflypl** [comment]
3. Saving issue: i could not reproduce it as well. I changed error handling a bit to display dialog with detailed info.

**Comment by pauljanes** [comment]
Hi Pawel. What do you mean by 3. Saving issue? in your comment above? Jayne had a problem with clicking the Add Activity button and nothing happened that Waldemar is looking into. Is that what you mean by Saving issue?

**Comment by dragonflypl** [comment]
Saving == Adding new

**Comment by wszarmach** [comment]
This issue contains too many tasks but it looks like they are all closed
