### ISSUE TITLE
Pressing add new activity button while internet is temporarily disconnected means it doesnt work even when the connection comes back

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#538]
If you open your laptop and the wifi connection is not yet established for instance and then you click on add new activity before it is established, then even once you have the wifi connection the button will no longer work. This could also happen if there is a temporary internet disconnection.

I believe this is probably what happened to Jayne.

To reproduce:

Go to Activities screen
Turn off your wifi connection
Click the add new activity button
Turn on your wifi connection
Keep clicking the add new activity button and nothing ever happens

I would expect the button to work once the connection is re-established. The user may not be technical enough to start trying to refresh, trying to go back and forth between screens to get it to work again etc.

**Comment by pauljanes** [comment]
The only difference between what I found above and what happened to Jayne is that Jayne said even doing a refresh she wasnt able to add a new activity. But she clearly had internet connection because once I added the activities she did a refresh and saw the new activities that I had created.

**Comment by pauljanes** [comment]
Waldemar asked me to get the JS console logs:

Failed to load resource: net::ERR_INTERNET_DISCONNECTED
dep-main.min-6e920730.js:10$routeChangeError, event={"name":"$routeChangeError","targetScope":"$SCOPE","defaultPrevented":false,"currentScope":"$SCOPE"} next={"params":{"organizationId":"O30002"},"pathParams":{},"loadedTemplateUrl":"admin/activity/admin-activity.html"}
dep-main.min-6e920730.js:10 GET https://jasify-schedule.appspot.com/build/img/edit.svg net::ERR_INTERNET_DISCONNECTED(anonymous function) @ dep-main.min-6e920730.js:10w @ dep-main.min-6e920730.js:10c @ dep-main.min-6e920730.js:10l @ dep-main.min-6e920730.js:10(anonymous function) @ dep-main.min-6e920730.js:10p.$eval @ dep-main.min-6e920730.js:11p.$digest @ dep-main.min-6e920730.js:11p.$apply @ dep-main.min-6e920730.js:11(anonymous function) @ jasify.min-e8cea5f6.js:2Q.event.dispatch @ dep-main.min-6e920730.js:6g.handle @ dep-main.min-6e920730.js:5
dep-main.min-6e920730.js:10 GET https://jasify-schedule.appspot.com/build/img/bin.svg net::ERR_INTERNET_DISCONNECTED

**Comment by dragonflypl** [comment]
I tried to reproduce it , what happens on my machine is that Save is spinning for a few seconds and then it displays error. Once connection is established clicking Save works. I'm using Wifi.

Stack trace shows error that occurs if users is trying to navigate to other page while connection. Once again, after wifi is connected, navigation works for me.

**Comment by dragonflypl** [comment]
But, tell her to check if other pages work. It sounds stupid, but I had issue similar to what she describes on Windows 8 - sometimes my modem looses signal, and after reconnecting it shows that connection is available, but internet does not work.

**Comment by pauljanes** [comment]
Did you try with the "Add Activity" (the + symbol) button (shown in screenshot) while your connection is down?

![screen shot 2015-06-22 at 23 14 03](https://cloud.githubusercontent.com/assets/9402268/8293264/9c419cf6-1934-11e5-9cbd-688034f4eb85.png)

**Comment by pauljanes** [comment]
"But, tell her to check if other pages work. It sounds stupid, but I had issue similar to what she describes on Windows 8 - sometimes my modem looses signal, and after reconnecting it shows that connection is available, but internet does not work."

Yes she was able to see the activities that I just added (by doing a refresh page) even though the button above was not working for her. So it means she must have had internet connection in order to see my newly created activities

**Comment by dragonflypl** [comment]
Indeed, with new activity is does not work. This one gonna be harder to resolve.

@krico : we need to catch gapi error in this case and show some kind of message to the user in this case. Basically if this happens it does not work because URL contains new activity hash. If it fails to load due to network issue, url stays the same. So when network is back, clicking does not trigger any Angular actions, because URL stays the same.

**Comment by pauljanes** [comment]
Can you force a refresh somehow? Because when user refreshes page it works again right?

**Comment by dragonflypl** [comment]
Yes, refresh is possible. But I was thinking about displaying a message "Connection issue...." with refresh button. Something similar is on gmail. In order to do it, we need to catch the error.

**Comment by pauljanes** [comment]
Ok cool sounds good

**Comment by krico** [comment]
I think all that we need to do is properly handle route resolve errors
