### ISSUE TITLE
Bug in booking of APs where one of the activities is fully booked

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#546]
If you take a look at the screenshots you see that there is a bug in the booking of APs where one of the activities is fully booked. We should prevent user getting to payment stage. You see in screenshot 1 that user has no select all next to the AP which is good, and they cannot tick the checkbox next to the fully booked activity. So at this point everything is correct. Well done.

However look at screenshot 2 and you see that when I tick the checkbox next to the second activity, I now see a select all checkbox next to the AP and am able to tick it and proceed to checkout to purchase the AP (which should not be possible). Whatever logic you have that suddenly makes a select all option appear when I select the second activity is wrong.

![screen shot 2015-06-23 at 17 39 28](https://cloud.githubusercontent.com/assets/9402268/8310373/bc813058-19cf-11e5-9ccb-73d3814405b9.png)
![screen shot 2015-06-23 at 17 39 48](https://cloud.githubusercontent.com/assets/9402268/8310372/bc80e24c-19cf-11e5-98a4-4920b419ee4f.png)
![screen shot 2015-06-23 at 17 40 02](https://cloud.githubusercontent.com/assets/9402268/8310374/bc82c2ba-19cf-11e5-9d6c-69a5f25712be.png)

**Comment by dragonflypl** [comment]
Fixed
