### ISSUE TITLE
Entering New Activity Type screen generates front end error

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#588]
```
TypeError: Cannot read property 'length' of undefined
    at n.unpack (farbtastic.js:284)
    at n.setColor (farbtastic.js:92)
    at Object.fn (form.helper.directives.js:339)
    at p.$get.p.$digest (angular.js:14397)
    at angular.js:14594
    at a (angular.js:4940)
    at angular.js:5328
```

**Comment by dragonflypl** [comment]
Is it happening always? How to reproduce it?

**Comment by wszarmach** [comment]
For me it was happening all the time

**Comment by wszarmach** [comment]
![screen shot 2015-07-13 at 20 16 59](https://cloud.githubusercontent.com/assets/9398950/8657130/226490c8-299c-11e5-91d5-28fb08f56558.png)
![screen shot 2015-07-13 at 20 17 09](https://cloud.githubusercontent.com/assets/9398950/8657132/2470bc8e-299c-11e5-89ce-c65337738618.png)

**Comment by wszarmach** [comment]
I managed to fix it by adding the following code in form.helper.directives.js. At startup the colour is not initialised.
```
angular.element(inputColorOutput).scope().$watch(inputColorOutput.attr('ng-model'), function (newValue) {
   if (typeof newValue !== 'undefined') {
         $.farbtastic($element).setColor(newValue);
   }
});
```

**Comment by wszarmach** [comment]
Fixed
