### ISSUE TITLE
On IE 11 the checkout window is a blank screen

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#590]
I tried to book something using IE 11. The checkout page shows as blank. If I try clicking tab I see small parts of the screen so it is clear there is something on the screen. Looks like some kind of display issue. Calling this a blocker as like Wally mentioned, many people still use IE.

![jasify_ie11](https://cloud.githubusercontent.com/assets/9402268/8639341/248a0c5e-28d7-11e5-9278-82d9869178b7.jpg)

**Comment by krico** [comment]
Could u see if there are any error on the JavaScript console please and
attach them here?

**Comment by pauljanes** [comment]
There is no error in the console. I checked. Its a page size issue as you can see the top of the buttons in the screenshot above, and if you click tab you can see the whole button

**Comment by krico** [comment]
This is definitely related to #557...
