### ISSUE TITLE
New Activity Package Activities selected does not update

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#613]
I selected Add Activity Package.
Selected some Activities but the Activities Selected value stayed the same.
![screen shot 2015-07-22 at 00 32 46](https://cloud.githubusercontent.com/assets/9398950/8814117/698b586a-3009-11e5-9b6c-5cc4538f46e6.png)

**Comment by dragonflypl** [comment]
This is duplicate of #599 . This is a bug in Angular - i've submitted it on their github and i'm waiting for solution
