### ISSUE TITLE
PROD: Shopping cart contains old selections that are no longer valid

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#617]
A month ago a user selected items via the widget. Today the user tried to use the widget again and found the old items were still selected.
Ideally items that can no longer be booked should be removed from the widget.

**Comment by krico** [comment]
Yes, this is frontend localStorage... We need to check the age of it I guess

**Comment by dragonflypl** [comment]
Just out of curiosity: why localStorage, not sessionStorage?

**Comment by pauljanes** [comment]
Yes I wondered too. Shouldnt it be just for the session?
