### ISSUE TITLE
Go live problem with cancel related logic - 3 spots reserved but only 2 subscribers

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#630]
Take a look at the screenshots below and you see that 3 places in this class are taken. Yet in the list of subscribers there are only 2 subscribers (I cannot screenshot that as there are users emails and I dont want to make that info public, but you can check yourself in the system and you will see there are only 2 real clients). Since all the testing I did was last night, all the cancel tasks should have executed by this morning and there should be only 2 places taken in this class by now.

This could cause us a big problem if J's classes show as full but there are still places left, because genuine clients would not be able to book even though there is space left and she could lose money.

As the mail has been sent out we need to look into this super urgently to make sure we know how it happened and to prevent it from happening again.

![screen shot 2015-07-28 at 10 02 32](https://cloud.githubusercontent.com/assets/9402268/8926590/321a93ca-3511-11e5-9497-6ba865ce396c.png)

**Comment by wszarmach** [comment]
Closed as part of #662
