### ISSUE TITLE
Why am I unable to delete organisation "Stacked! bootcamp"?

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#635]
I am trying to delete organisation "Stacked! bootcamp" as she no longer operates, but when I press delete nothing happens.

I checked and there are no activities defined for this org, and I deleted the one activity type that existed. So I am not sure what is preventing me from deleting it now. If there is some kind of condition it should be displayed to the user so they know why they cant delete it. At the moment it is a mystery to me why I cant delete it.

**Comment by wszarmach** [comment]
As an fyi; the organisation has 1 member associated with it. This is what is currently preventing it from being deleted.

**Comment by pauljanes** [comment]
Ah ok cool. I will remove her then. Would be great that these messages are shown on frontend.

**Comment by wszarmach** [comment]
Yes. thats a bug that we will fix as it happens in many places
