### ISSUE TITLE
Clicking on Schedule gives exception

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#705]
It might be because I have not yet signed up to any activities with my pauljanes1979@gmail.com user, but it gives an exception when I click on "Schedule". Although the exception seems to refer to No Excuses judging by the org id that it mentions.

![screen shot 2015-09-22 at 15 27 22](https://cloud.githubusercontent.com/assets/9402268/10019614/ac83ba34-613e-11e5-83cc-eacef02e1e21.png)

**Comment by wszarmach** [comment]
This is due to activities that were deleted in January 2015. I have removed the subscriptions that referenced these and will put in code to catch, log, and continue of these happen again.
