### ISSUE TITLE
As org admin I get an error when clicking on Admin Balances

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#708]
I logged in to the link chris gave me to test on as org admin

I clicked on Admin then Balances and I get the error in the screenshot below

![screen shot 2015-09-22 at 17 47 45](https://cloud.githubusercontent.com/assets/9402268/10023382/27a87eb2-6152-11e5-8810-4efa1fafd4e5.png)

**Comment by pauljanes** [comment]
as admin though it works ok so I guess the issue is permission related ie whether user is admin or org admin

**Comment by wszarmach** [comment]
Currently a new org will not have an account created until a transfer is completed/accepted. This means that when the front end asks for the account information an exception is raised.

**Comment by wszarmach** [comment]
Will be fixed in #711
