### ISSUE TITLE
On the invoice we still have "Please execute the payment in the next 3 days"

### ISSUE THREAD

**Issue by pauljanes** [krico/jas#723]
I just did an electronic invoice payment and in the email it says "Please execute the payment in the next 3 days". Both Jayne and I think this is very confusing as it suggests the person can start the transfer in 3 days time and doesn't mention that they we need to receive payment BEFORE the activity starts.

Remove BOTH mentions of 3 days (it appears twice in the email - once in the above statement and once next to the date) and just include the following statement:

"If payment is not received in our bank account at least 24 hours in advance of the activity start date, the subscriptions corresponding to this invoice are liable to be cancelled. Should payment then arrive post-cancellation, your Jasify account will be credited the full amount minus the electronic invoice handling fee. These credits can then be used to purchase other items of an equal value."

**Comment by pauljanes** [comment]
Thinking about it though the 3 days seems pretty random anyhow. What we actually want is that payment is received at least 24 hours in advance of the activity start date.

We shouldn't even mention 3 days. We should say "If payment is not received in our account at least 24 hours in advance of the activity start date, your subscriptions are liable to be cancelled."

**Comment by wszarmach** [comment]
Fixed as part of todays release although a better wording may be required in the future.
