### ISSUE TITLE
Checkout payment options are not clear

### ISSUE THREAD

**Issue by wszarmach** [krico/jas#725]
Currently the payment options are a drop down list and assume that the user knows that the list is interactive and more options are available. This should be changed to a radio button selection so it is clear to the user what payment options are available

**Comment by pauljanes** [comment]
Very good point. I was thinking that too that they might not know there are more options in dropdown. One thing I would say though is do we want to encourage bank transfers if it means the paypal volume drops below 4k a month? We can always default the radio button to paypal or give some kind of psychological encouragement like "Use Paypal for a quick and easy checkout" then "Use old-fashioned Electronic Invoice"

**Comment by wszarmach** [comment]
If we do promote an option then it seems to me we should promote what will make us the most revenue but at this time I would just do an alphabetic list with no radio button selected
